language: node_js
node_js: stable

sudo: false

addons:
  firefox: latest
  chrome: stable

os:
  - linux

after_failure:
  - cat /home/travis/build/alobaton/nebular-angular-seed/npm-debug.log

branches:
  only: master

notifications:
  email: false

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run tests.all
