version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_dev
    command: npm start
    container_name: nebular-angular-seed-dev
    image: nebular-angular-seed/dev
    volumes:
      - ./src:/home/node/nebular-angular-seed/src
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
